---
- name: 'add wezterm APT repository'
  become: true
  ansible.builtin.deb822_repository:
    name: wezterm
    uris: 'https://apt.fury.io/wez'
    signed_by: 'https://apt.fury.io/wez/gpg.key'
    suites: '*'
    components: '*'
    architectures: amd64
  notify: update apt cache

- name: 'flush handlers'
  ansible.builtin.meta: flush_handlers

- name: 'install wezterm'
  become: true
  apt:
    state: latest
    name: 'wezterm-nightly'

- name: 'check if wezterm is in alternatives'
  become: true
  command: 'update-alternatives --list x-terminal-emulator'
  register: alternatives_output
  changed_when: false

- name: 'add wezterm to x-terminal-emulator alternatives'
  become: true
  command: 'update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator $(which wezterm) 50'
  when: '"wezterm" not in alternatives_output.stdout'

- name: 'check current default x-terminal-emulator'
  become: true
  shell: 'update-alternatives --query x-terminal-emulator | grep "Value: "'
  register: current_terminal
  changed_when: false

- name: 'set wezterm as default terminal emulator'
  become: true
  command: 'update-alternatives --set x-terminal-emulator $(which wezterm)'
  when: '"wezterm" not in current_terminal.stdout'
