---
- name: 'Clone neovim'
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: '{{ dir_sources }}/neovim/neovim'
    clone: true
    update: true
    force: true
  register: clone

- when: clone.changed
  block:
    - name: 'Clean neovim'
      command: 'make distclean'
      args:
        chdir: '{{ dir_sources }}/neovim/neovim'

    - name: 'Build neovim'
      command: 'make CMAKE_BUILD_TYPE=RelWithDebInfo -j 4'
      args:
        chdir: '{{ dir_sources }}/neovim/neovim'

    - name: 'Remove existing neovim runtime files'
      become: true
      shell: 'rm -rf $(nvim --headless --clean -n -c "echo \$VIM | q")'

    - name: 'Install neovim'
      become: true
      command: 'make install'
      args:
        chdir: '{{ dir_sources }}/neovim/neovim'

- name: 'Install python neovim module'
  pip:
    name: pynvim
    state: latest

- name: 'Install NodeJS neovim module'
  become: true
  npm:
    name: neovim
    global: true
    state: latest
