---
- name: 'add ghostty APT repository'
  become: true
  ansible.builtin.deb822_repository:
    name: ghostty
    uris: https://ppa.launchpadcontent.net/mkasberg/ghostty-ubuntu/ubuntu
    signed_by: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0721fdf5fecb88dc6920361657c8ef455ceae491
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
  notify: update apt cache

- name: 'flush handlers'
  ansible.builtin.meta: flush_handlers

- name: 'install ghostty'
  become: true
  ansible.builtin.package:
    state: latest
    name: ghostty
