---
- name: 'create systemd service'
  become: true
  copy:
    src: charge-thresholds.service
    dest: /etc/systemd/system/charge-thresholds.service
  register: charge_thresholds_service

- name: 'enable and start systemd service'
  become: true
  systemd:
    name: charge-thresholds
    enabled: true
    state: started
  when: charge_thresholds_service.changed
