---
- name: Copy systemd unit
  copy:
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
  loop:
    - charge-thresholds
    - profile
  register: service

- name: Enable and start service
  systemd_service:
    name: "{{ item.item }}"
    enabled: true
    state: started
  when: item.changed
  loop: "{{ service.results }}"
