---
- name: 'Download Nerd Font'
  get_url:
    url: '{{ nerd_font_url }}'
    dest: '{{ dir_sources }}/{{ nerd_font_file }}'
  register: download

- when: download.changed
  block:
    - name: 'Create font dir'
      file:
        path: '~/.local/share/fonts'
        state: directory

    - name: 'Unzip Nerd Font'
      unarchive: 
        src: '{{ dir_sources }}/{{ nerd_font_file }}'
        dest: '~/.local/share/fonts'

    - name: 'Remove Windows Fonts'
      file:
        path: '{{ item }}'
        state: absent
      with_fileglob: '~/.local/share/fonts/*Windows*'

    - name: 'Install Nerd Font'
      command: 'fc-cache -fv'
