---
- name: 'install go'
  include_role:
    name: geerlingguy.go
    apply:
      become: true

- name: Create symlink for Go binary
  become: true
  file:
    src: /usr/local/go/bin/go
    dest: /usr/local/bin/go
    state: link
