---
- name: add git ppa
  apt_repository:
    repo: 'ppa:git-core/ppa'

- name: install git
  become: true
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    name:
      - git
