---
- name: 'Clone ctags'
  git:
    repo: 'https://github.com/universal-ctags/ctags.git'
    dest: '{{ dir_ctags }}'
    clone: true
    update: true
    force: true
  register: clone

- when: clone.changed
  block:
    - name: 'Generate ctags config'
      command: './autogen.sh'
      args:
        chdir: '{{ dir_ctags }}'

    - name: 'Configure ctags'
      command: './configure'
      args:
        chdir: '{{ dir_ctags }}'

    - name: 'Build ctags'
      command: 'make -j 4'
      args:
        chdir: '{{ dir_ctags }}'

    - name: 'Install ctags'
      become: true
      command: 'make install'
      args:
        chdir: '{{ dir_ctags }}'

    - name: 'Clean ctags'
      shell: 'make clean-local && make clean'
      args:
        chdir: '{{ dir_ctags }}'
