# $schema: https://jj-vcs.github.io/jj/prerelease/config-schema.json

[user]
name = "Caleb White"
email = "cdwhite3@pm.me"

[aliases]
fetch = { definition = ["git", "fetch", "--all-remotes"], doc = "Fetch changes from all git remotes" }
g = { definition = ["git"], doc = "Shorthand for git subcommands" }
push = { definition = ["git", "push"], doc = "Push bookmarks to git remote" }
retrunk = { definition = ["rebase", "-d", "trunk()"], doc = "Rebase current change onto trunk" }
sudo = { definition = ["--ignore-immutable"], doc = "Run subcommand while ignoring immutable commits" }
tug = { definition = ["bookmark", "advance"], doc = "Advance current bookmark to the working copy" }

[colors]
# "diff token" = { underline = false }

[git]
private-commits = "wip() | private()"
sign-on-push = true

[revsets]
bookmark-advance-to = 'heads(::@ & mutable() & ~description(exact:"") & (~empty() | merges()))'

[revset-aliases]
'wip()' = { definition = 'description(glob:"wip:*")', doc = "Revisions marked as work-in-progress via description" }
'private()' = { definition = 'description(glob:"private:*")', doc = "Revisions marked as private via description" }
'tip()' = { definition = 'exactly(heads(@::), 1)', doc = "The single head revision of the current anonymous branch" }
'why_immutable(r)' = { definition = '(r & immutable()) | roots(r:: & immutable_heads())', doc = "Revisions explaining why the given revision is immutable" }
log = { definition = "ancestors(reachable(@, trunk()..), 2)", doc = "Extended ancestors for log showing context around working copy" }

[signing]
behavior = "drop"
backend = "gpg"

[snapshot]
auto-update-stale = true

[templates]
draft_commit_description = 'builtin_draft_commit_description_with_diff'
new_description = '''
if(parents.len() > 1, join(" ",
  "Merge",
  parents.skip(1).map(|p| bookmarks_or_hash(p)).join(", "),
  "into",
  bookmarks_or_hash(parents.first()),
))
'''
git_push_bookmark = '"calebdw/push-" ++ change_id.short()'

[template-aliases]
'bookmarks_or_hash(c)' = { definition = 'coalesce(c.bookmarks().map(|b| b.name()).join(", "), c.commit_id().short())', doc = "Return joined bookmark names or fallback to short commit id" }

[ui]
default-command = "log"
diff-editor = ["nvim", ".", "-c", "DiffEditor $left $right $output"]
show-cryptographic-signatures = true
log-synthetic-elided-nodes = true

[ui.movement]
# edit = true

[fix.tools.rustfmt]
command = ["cargo", "fmt", "--", "--emit=stdout"]
patterns = ["glob:'**/*.rs'"]
